#! /bin/sh
### BEGIN INIT INFO
# Provides: roomserver
# Required-Start: $remote_fs $syslog
# Required-Stop: $remote_fs $syslog
# Default-Start: 2 3 4 5
# Default-Stop: 0 1 6
# Short-Description: Roomserver
# Description: This file starts and stops webrtc room server
# 
### END INIT INFO
# 1-Copy to /etc/init.d
# 2-sudo update-rc.d roomserver defaults
# 3-sudo reboot
export JAVA_HOME=/usr/lib/jvm/java-8-oracle
export ROOM_DIR=/home/ubuntu/RTC/apprtc
case "$1" in
 start)
   cd $ROOM_DIR && $ROOM_DIR/startup.sh > /var/log/roomserver.log 2>&1
   ;;
 stop)
   sleep 10
   ;;
 *)
   echo "Usage: tomcat {start|stop}" >&2
   exit 3
   ;;
esac
